"""Project setup and synthetic data preparation for the simulation CLI."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import typer

from pipeline.cli.simulation import examples, templates
from pipeline.cli.simulation.paths import write_yaml
from pipeline.cli.simulation.presets import PRESETS, Preset


RESET_ALLOWLIST = (
    "config.yaml",
    "pyproject.toml",
    "configs",
    "data",
    "results",
    "logs",
    "scripts",
)


def normalize_generated_synthetic_layout(
    project_dir: Path, 
    scale_name: str, 
    num_clients: int
) -> None:
    """Move generator output into the user-facing `data/center_*` layout.

    The existing synthetic generator writes `data/<scale>/center_*`. The CLI
    project config points Flower and validation at `data/center_*`, so this
    adapter keeps installed projects free of repository-style paths.

    Args:
        project_dir: Simulation project root.
        scale_name: Synthetic scale name generated by the existing generator.
        num_clients: Number of center directories to normalize.

    Returns:
        None. Moves files in place when generator output exists.
    """
    generated_scale_dir = project_dir / "data" / scale_name
    if not generated_scale_dir.exists():
        return
    for center_id in range(1, num_clients + 1):
        source_dir = generated_scale_dir / f"center_{center_id}"
        target_dir = project_dir / "data" / f"center_{center_id}"
        target_dir.mkdir(parents=True, exist_ok=True)
        if not source_dir.exists():
            continue
        for source in source_dir.iterdir():
            if source.is_file():
                target = target_dir / source.name
                if target.exists():
                    target.unlink()
                shutil.move(str(source), str(target))
        try:
            source_dir.rmdir()
        except OSError:
            pass


def generate_synthetic_data(
    project_dir: Path,
    preset_name: str,
    scale_name: str,
    seed: int | None,
) -> None:
    """Generate synthetic PLINK data through the existing pipeline generator.

    Args:
        project_dir: Simulation project root.
        preset_name: Preset key used to look up client count.
        scale_name: Synthetic generator scale name, such as `tiny`.
        seed: Optional random seed forwarded to the generator.

    Returns:
        None. Writes PLINK files under the project data directory.
    """
    from pipeline.simulation.simulated_data.generate_synthetic_data import (
        SyntheticDataGenerator,
    )

    generator = SyntheticDataGenerator(output_dir=project_dir / "data")
    generator.generate_scale(scale_name, partition_strategy="even", seed=seed)
    normalize_generated_synthetic_layout(
        project_dir,
        scale_name,
        PRESETS[preset_name].num_clients,
    )


def _is_initialized_project(project_dir: Path) -> bool:
    """Return whether a directory looks like a CLI-initialized project.

    Args:
        project_dir: Candidate simulation project root.

    Returns:
        True when the directory contains a `fedgwas.yaml` marker created by
        `fedgwas-sim init`; otherwise False.
    """
    config_path = project_dir / "fedgwas.yaml"
    if not config_path.exists():
        return False
    try:
        import yaml

        config = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    except Exception:
        return False
    return config.get("mode") == "simulation" and config.get("project_state") in {"initialized", "configured"}


def _require_simulation_project(project_dir: Path) -> None:
    """Require a directory to contain a simulation project marker.

    Args:
        project_dir: Candidate project root.

    Returns:
        None when the directory is a simulation project.

    Raises:
        typer.BadParameter: If `fedgwas.yaml` is missing or not a simulation
            project config.
    """
    if not _is_initialized_project(project_dir):
        raise typer.BadParameter(f"{project_dir} is not a FedGWAS simulation project.")


def _safe_project_child(project_dir: Path, relative_path: str) -> Path:
    """Resolve an allowlisted child path and require it to stay in the project.

    Args:
        project_dir: Simulation project root.
        relative_path: Allowlisted project-relative path.

    Returns:
        Absolute child path inside the project root.

    Raises:
        typer.BadParameter: If resolution would escape `project_dir`.
    """
    root = project_dir.resolve()
    child = (root / relative_path).resolve()
    try:
        child.relative_to(root)
    except ValueError as exc:
        raise typer.BadParameter(f"Refusing to reset path outside project: {child}") from exc
    return child


def _ensure_project_dirs(project_dir: Path, num_clients: int = 0) -> None:
    """Create the standard simulation project directories.

    Args:
        project_dir: Simulation project root.
        num_clients: Optional number of center result/data directories to create.

    Returns:
        None. Directories are created if missing.
    """
    project_dir.mkdir(parents=True, exist_ok=True)
    for dirname in ("configs", "data", "results", "logs"):
        (project_dir / dirname).mkdir(exist_ok=True)
    for center_id in range(1, num_clients + 1):
        (project_dir / "data" / f"center_{center_id}").mkdir(parents=True, exist_ok=True)
        (project_dir / "results" / f"center_{center_id}" / "intermediate").mkdir(parents=True, exist_ok=True)
        (project_dir / "results" / f"center_{center_id}" / "logs").mkdir(parents=True, exist_ok=True)
    if num_clients:
        (project_dir / "results" / "server" / "intermediate").mkdir(parents=True, exist_ok=True)
        (project_dir / "results" / "server" / "logs").mkdir(parents=True, exist_ok=True)


def init_project(project_dir: Path, force: bool = False) -> None:
    """Initialize a simulation project directory without configuring an experiment.

    Args:
        project_dir: Destination simulation project root.
        force: Whether to allow writing into a non-empty directory.

    Returns:
        None. Writes base project files and creates standard directories.

    Raises:
        typer.BadParameter: If the directory is non-empty and not already a
            simulation project unless `force` is true.
    """
    if project_dir.exists() and any(project_dir.iterdir()) and not force and not _is_initialized_project(project_dir):
        raise typer.BadParameter(f"{project_dir} already exists and is not empty. Use --force to initialize anyway.")

    _ensure_project_dirs(project_dir)
    project_name = project_dir.name or "fedgwas-simulation-project"
    write_yaml(project_dir / "fedgwas.yaml", templates.base_project_config(project_name))
    write_yaml(project_dir / "config.yaml", templates.base_experiment_config(project_name))
    (project_dir / "pyproject.toml").write_text(templates.project_pyproject(1), encoding="utf-8")


def reset_project(
    project_dir: Path,
    *,
    keep_data: bool = False,
    keep_configs: bool = False,
    keep_results: bool = False,
) -> list[Path]:
    """Reset a simulation project back to the base initialized structure.

    Args:
        project_dir: Simulation project root.
        keep_data: Whether to preserve the `data/` directory.
        keep_configs: Whether to preserve the `configs/` directory.
        keep_results: Whether to preserve the `results/` directory.

    Returns:
        List of project child paths that were removed.

    Raises:
        typer.BadParameter: If `project_dir` is not a simulation project.

    Only fixed, CLI-managed paths are eligible for removal. Unknown user files
    in the project root are intentionally left untouched.
    """
    _require_simulation_project(project_dir)
    skipped = set()
    if keep_data:
        skipped.add("data")
    if keep_configs:
        skipped.add("configs")
    if keep_results:
        skipped.add("results")

    removed: list[Path] = []
    for relative_path in RESET_ALLOWLIST:
        if relative_path in skipped:
            continue
        target = _safe_project_child(project_dir, relative_path)
        if not target.exists():
            continue
        if target.is_dir():
            shutil.rmtree(target)
        else:
            target.unlink()
        removed.append(target)

    init_project(project_dir, force=True)
    return removed


def create_project_from_example(
    project_dir: Path,
    example_name: str,
    force: bool = False,
    prepare_data: bool = True,
    seed: int | None = None,
) -> None:
    """Create a simulation project from a built-in example template.

    Args:
        project_dir: Destination simulation project root.
        example_name: Name from `examples.EXAMPLES`.
        force: Whether to allow writing into a non-empty directory.
        prepare_data: Whether to prepare the example's configured data after
            writing the project files.
        seed: Optional synthetic data seed for reproducible example data.

    Returns:
        None. Writes configs and creates project directories.

    Raises:
        typer.BadParameter: If the example is unknown or the destination is not
            safe to write.
    """
    spec = examples.EXAMPLES.get(example_name)
    if spec is None:
        allowed = ", ".join(examples.EXAMPLES)
        raise typer.BadParameter(f"Unknown example '{example_name}'. Choose one of: {allowed}.")
    if project_dir.exists() and any(project_dir.iterdir()) and not force and not _is_initialized_project(project_dir):
        raise typer.BadParameter(f"{project_dir} already exists and is not empty. Use --force to initialize anyway.")

    _ensure_project_dirs(project_dir, spec.num_clients)
    write_yaml(project_dir / "fedgwas.yaml", examples.example_project_config(spec))
    write_yaml(project_dir / "config.yaml", examples.example_experiment_config(spec))
    (project_dir / "pyproject.toml").write_text(templates.project_pyproject(spec.num_clients), encoding="utf-8")
    write_yaml(project_dir / "configs" / "server.yaml", templates.server_config())
    for center_id in range(1, spec.num_clients + 1):
        write_yaml(project_dir / "configs" / f"center_{center_id}.yaml", examples.example_center_config(spec, center_id))
    if not spec.preset:
        return
    preset = PRESETS.get(spec.preset)
    if preset is None:
        return
    if preset.synthetic and preset.scale:
        if prepare_data:
            generate_synthetic_data(project_dir, preset.name, preset.scale, seed)
        return
    if not prepare_data:
        templates.write_real_preset_scripts(project_dir, preset)
        return
    prepare_real_data(project_dir, preset, prepare_data)


def prepare_real_data(project_dir: Path, preset: Preset, download: bool) -> None:
    """Write and optionally execute the real-data preparation script.

    Args:
        project_dir: Simulation project root.
        preset: Real-data preset selected by `setup-experiment`.
        download: Whether to execute the generated preparation script.

    Returns:
        None. Writes the preparation script and, when requested, exits on script
        failure through `subprocess.run(check=True)`.
    """
    templates.write_real_preset_scripts(project_dir, preset)
    if not download:
        return
    subprocess.run([sys.executable, str(project_dir / "scripts" / "prepare_data.py"), "--download"], cwd=project_dir, check=True)


def create_project(
    project_dir: Path, 
    preset: Preset, 
    force: bool, 
    seed: int | None,
    download_real_data: bool = True,
) -> None:
    """Create a simulation project directory from a preset.

    This is the main scaffold operation behind `setup-experiment`: it creates
    stable directories, writes all YAML/TOML config files, then either generates
    synthetic data or writes real-data preparation templates.

    Args:
        project_dir: Destination simulation project root.
        preset: Preset selected by `setup-experiment`.
        force: Whether to allow writing template files into a non-empty project.
        seed: Optional synthetic data seed.
        download_real_data: Whether real-data presets should execute their
            preparation script after writing configs.

    Returns:
        None. Creates directories and files on disk.

    Raises:
        typer.BadParameter: If `project_dir` is non-empty and `force` is false.
    """
    if project_dir.exists() and any(project_dir.iterdir()) and not force and not _is_initialized_project(project_dir):
        raise typer.BadParameter(
            f"{project_dir} already exists and is not empty. Use --force to overwrite template files."
        )

    _ensure_project_dirs(project_dir, preset.num_clients)

    write_yaml(project_dir / "fedgwas.yaml", templates.project_config(preset, seed))
    write_yaml(project_dir / "config.yaml", templates.experiment_config(preset))
    (project_dir / "pyproject.toml").write_text(
        templates.project_pyproject(preset.num_clients),
        encoding="utf-8",
    )
    write_yaml(project_dir / "configs" / "server.yaml", templates.server_config())
    for center_id in range(1, preset.num_clients + 1):
        write_yaml(project_dir / "configs" / f"center_{center_id}.yaml", templates.center_config(preset, center_id))

    if preset.synthetic and preset.scale:
        generate_synthetic_data(project_dir, preset.name, preset.scale, seed)
    else:
        prepare_real_data(project_dir, preset, download_real_data)
